services:
  postgres:
    # Reiniciar siempre
    restart: always
    # Eliminamos los puertos abiertos al exterior
    ports: []

  app-blue:
    image: ivancarreras/sportsclub:latest
    restart: always

  app-green:
    image: ivancarreras/sportsclub:latest
    restart: always

  nginx:
    restart: always
    ports:
      - "80:80" # Asignamos 80:80 al exterior